### ISSUE TITLE
Broken link..

### ISSUE THREAD

**Issue by doyoungim999** [IBM-Bluemix-Docs/EventManagement#1]
https://www.ibm.com/support/knowledgecenter/SSURRN/com.ibm.cem.doc//docs/services/EventManagement/em_incomingwebhook.html  

in https://cloud.ibm.com/docs/services/EventManagement?topic=cloudeventmanagement-Untitled#examples-mapping-json-attributes-to-cloud-event-management-attributes

**Comment by hobbert** [comment]
Fixed.
https://cloud.ibm.com/docs/services/EventManagement?topic=cloudeventmanagement-Untitled#examples-mapping-json-attributes-to-cloud-event-management-attributes
